### ISSUE TITLE
Intermediate Block Generation

### ISSUE THREAD

**Issue by jeffz0** [xialeiliu/GFR-IL#2]
Hi, 

First off, congrats on the paper and thanks for released code for your work! In Table 2 of the paper, you compared generation of different intermediate blocks. Are you generating feature maps for blocks 1-3? If so, we would need to change the discriminator and generator architecture right?

Thanks,

Jeff

**Comment by xialeiliu** [comment]
Yes, you are right. To generate feature maps, we need to change the network architecture. Since different blocks have different resolutions and channels.

**Comment by jeffz0** [comment]
Thanks for the prompt response Xialei! What is the architecture for block 1-3 and image level generation? And were your learning hyperparameters the same as what you specified in your paper, or did you tune separate hyperparameters for each experiment in Table 2? 

Thanks a lot,

Jeff

**Comment by xialeiliu** [comment]
The architecture is quite straightforward to change from 3 channels (image generation) to N channels with couples of convolution layers(N is number of feature maps for one specific block). We indeed have tried different parameters, But in the end, we could not train the model well. It is more challenging than we thought. We believe that there should be more work on how to generate intermediate features and how to evaluate them.

**Comment by jeffz0** [comment]
That makes sense and I agree. Personally, I've had issues generating intermediate feature maps for an incremental learning scenario as well. Thanks again for the responses.
