### ISSUE TITLE
results replication

### ISSUE THREAD

**Issue by webcsm** [xialeiliu/GFR-IL#6]
Hi @xialeiliu , congratulations on your work! As far as I could see the released code only accounts for the proposed method. Do you intend to release the code you used to compute the baselines in Figures 4 and 5? Thanks.

**Comment by xialeiliu** [comment]
Thanks! I think you can find the released code of other methods on Github. We also used the publicly available code for those results.

**Comment by webcsm** [comment]
Thank you!
